language: java
jdk:
  - oraclejdk8
install:
  - sh -c 'mvn install -DskipTests=true'
  - sh -c 'cd jOOQ-examples/jOOQ-spring-example && mvn install -DskipTests=true'
  - sh -c 'cd jOOQ-examples/jOOQ-spring-boot-example && mvn install -DskipTests=true'
  - sh -c 'cd jOOQ-examples/jOOQ-flyway-example && mvn install -DskipTests=true'
  - sh -c 'cd jOOQ-examples/jOOQ-nashorn-example && mvn install -DskipTests=true'
  - sh -c 'cd jOOQ-examples/jOOQ-spring-guice-example && mvn install -DskipTests=true'
script:
  - sh -c 'mvn test'
  - sh -c 'cd jOOQ-examples/jOOQ-spring-example && mvn test'
  - sh -c 'cd jOOQ-examples/jOOQ-spring-boot-example && mvn test'
  - sh -c 'cd jOOQ-examples/jOOQ-flyway-example && mvn test'
  - sh -c 'cd jOOQ-examples/jOOQ-nashorn-example && mvn test'
  - sh -c 'cd jOOQ-examples/jOOQ-spring-guice-example && mvn test'
cache:
  directories:
    - $HOME/.m2/repository
